name: 'cars_dbt'
version: '1.0'
config-version: 2

profile: 'cars_dbt'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Глобальные настройки
models:
  cars_dbt:
    +materialized: view
    +on_schema_change: append_new_columns

    # RAW — только source, моделей нет
    raw:
      +enabled: false

    # STAGING — представления в схеме staging
    staging:
      +materialized: view
      +schema: staging

    # Marts
    marts:
      +materialized: table
      +schema: mart

      fact:
        +schema: fact
        +materialized: table

      dashboards:
        +schema: mart
        +materialized: table